# Generated by Django 4.2.7 on 2025-07-16 06:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='elevator_pitch',
            field=models.TextField(blank=True, help_text='Brief description of your project'),
        ),
        migrations.AddField(
            model_name='project',
            name='story_content',
            field=models.TextField(blank=True, help_text='Rich text content for project story'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='WorkAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_name', models.CharField(help_text='Name of the external contributor', max_length=200)),
                ('credit_description', models.TextField(help_text='Description of their contribution')),
                ('link', models.URLField(blank=True, help_text='Optional link to their work or profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_attributions', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Tool', 'Tool')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the item')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, help_text='Optional image of the item', null=True, upload_to='bom_images/')),
                ('link', models.URLField(blank=True, help_text='Optional purchase or reference link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_materials', to='api.project')),
            ],
            options={
                'ordering': ['item_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('Code', 'Code'), ('Schematic', 'Schematic'), ('CAD', 'CAD')], max_length=20)),
                ('title', models.CharField(help_text='Title for this attachment', max_length=200)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('repository_link', models.URLField(blank=True, help_text='Link to external repository (e.g., GitHub)')),
                ('description', models.TextField(blank=True, help_text='Optional description of the attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.project')),
            ],
            options={
                'ordering': ['attachment_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.TextField(help_text="Describe this member's contribution to the project")),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
