# Generated by Django 4.2.7 on 2025-07-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_elevator_pitch_project_story_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('Manage', 'Manage'), ('Read', 'Read')], default='Read', max_length=10),
        ),
    ]
