# Generated by Django 4.2.7 on 2025-07-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSlideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(help_text='Original PowerPoint (.ppt/.pptx) or PDF file', upload_to='project_slideshows/')),
                ('title', models.CharField(blank=True, help_text='Optional title for the slideshow', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the slideshow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slideshow', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlideshowSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.IntegerField(help_text='Order of the slide in the presentation')),
                ('image', models.ImageField(help_text='Converted slide image', upload_to='slideshow_slides/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slideshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='api.projectslideshow')),
            ],
            options={
                'ordering': ['slide_number'],
                'unique_together': {('slideshow', 'slide_number')},
            },
        ),
    ]
