# Generated by Django 4.2.7 on 2025-07-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_projectslideshow_slideshowslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
