# Generated by Django 4.2.7 on 2025-07-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('private', 'Private'), ('rejected', 'Rejected')], default='draft', max_length=10),
        ),
    ]
