# Generated by Django 4.2.7 on 2025-07-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='companies',
            field=models.JSONField(blank=True, default=list, help_text='List of company entries with company name and role'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='List of education entries with university and major'),
        ),
    ]
